FROM golang:1.25-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY internal/adapters/db ./internal/adapters/db

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -buildvcs=false -ldflags='-w -s' \
    -o /migrate ./internal/adapters/db/postgres

FROM gcr.io/distroless/static-debian12 AS build-release-stage

WORKDIR /

COPY --from=build-stage /migrate /migrate

USER nonroot:nonroot

ENTRYPOINT ["/migrate"]
